name: Backend CI

on:
  pull_request:
    paths:
      - "/be-present-backend/**"
    types:
      - opened
      - synchronize

jobs:
  merge-backend:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: v18.17.0

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./be-present-backend

      - name: Lint with yarn
        run: yarn lint
        working-directory: ./be-present-backend
